### ISSUE TITLE
`wskazowka=TRUE` argument

### ISSUE THREAD

**Issue by wchodor** [BetaAndBit/PieczaraPietraszki#1]
I am wondering whether I should change `wskazowka` parameter into an english version `tip`. 
This would require from me to change some parts of the `proton` function's body. 
@pbiecek  What do you think?

**Comment by pbiecek** [comment]
Maybe 'hint'?
I think it is more common in games
P

Dnia 18.11.2015 o godz. 10:13 Witold Chodor notifications@github.com napisał(a):

**Comment by wchodor** [comment]
OK, that's a good idea. I will use `hint` instead of `wskazowka`.
