### ISSUE TITLE
zzz file in polish version of proton

### ISSUE THREAD

**Issue by wchodor** [BetaAndBit/PieczaraPietraszki#10]

**Comment by wchodor** [comment]
I noticed a bug while reviewing your code. Take a look at my comment here:
https://github.com/BetaAndBit/PieczaraPietraszki/commit/fd32af0830331fd12cdb8630ee17ba269d47ba0a

**Comment by pbiecek** [comment]
What OS are you using?

**Comment by wchodor** [comment]
I'm using windows

**Comment by pbiecek** [comment]
Could you reinstall the proton package and check if comments are displayed correctly?
after
library(proton)
proton(wskazowka=T)

**Comment by wchodor** [comment]
I got this:

```
> library(proton)
NA

Attaching package: ‘proton’

The following objects are masked _by_ ‘.GlobalEnv’:

    logowania, pracownicy

> proton()
NA
> 
```

**Comment by wchodor** [comment]
By the way. Shouldn't we differ package names for polish and english versions of this package?

**Comment by pbiecek** [comment]
Polish version will not be accepted on CRAN because has non ASCII
characters.
So I am going to upload only english version.

btw: I cannot replicate your error.

What is your Sys.getlocale() ?

2015-11-23 22:57 GMT+01:00 Witold Chodor notifications@github.com:

> By the way. Shouldn't we differ package names for polish and english
> versions of this package?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/10#issuecomment-159078366
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
```
> Sys.getlocale()
[1] "LC_COLLATE=Polish_Poland.1250;LC_CTYPE=Polish_Poland.1250;LC_MONETARY=Polish_Poland.1250;LC_NUMERIC=C;LC_TIME=Polish_Poland.1250"
> 

```

**Comment by pbiecek** [comment]
I have the same. Could you pass the sessionInfo()?

2015-11-23 23:15 GMT+01:00 Witold Chodor notifications@github.com:

> > Sys.getlocale()
> > [1] "LC_COLLATE=Polish_Poland.1250;LC_CTYPE=Polish_Poland.1250;LC_MONETARY=Polish_Poland.1250;LC_NUMERIC=C;LC_TIME=Polish_Poland.1250"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/10#issuecomment-159084283
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
``````
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] proton_0.1     devtools_1.9.1

loaded via a namespace (and not attached):
 [1] httr_1.0.0        R6_2.1.1          magrittr_1.5      tools_3.2.2       rstudioapi_0.3.1 
 [6] curl_0.9.3        memoise_0.2.1     rstudio_0.98.1103 stringi_1.0-1     stringr_1.0.0    
[11] digest_0.6.8     
> ```
``````

**Comment by wchodor** [comment]
I think that if it is the problem with my computer so we should leave it.

**Comment by pbiecek** [comment]
Could you check new newest version of package?

2015-11-23 23:32 GMT+01:00 Witold Chodor notifications@github.com:

> I think that if it is the problem with my computer so we should leave it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/10#issuecomment-159088923
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
It is now like that:

```
proton.host.instr.w 
"Aby z ka<bf>dej linii wy<b3>uska<e6> tylko nazw<ea> instrukcji (napis do spacji), mo<bf>esz wykorzysta<e6> funkcj<ea> `gsub` lub `strsplit`.\nPo wy<b3>uskaniu tych instrukcji, sprawd<9f> jak cz<ea>sto, kt<f3>ra instrukcja jest u<bf>ywana. Mo<bf>e oka<bf>e si<ea>, <bf>e kt<f3>ra<9c> z instrukcji wygl<b9>da jak has<b3>o?\n\nJe<bf>eli znajdziesz co<9c> co wygl<b9>da jak has<b3>o, u<bf>yj komendy `proton(action = \"login\", login=\"XYZ\", password=\"ABC\")` aby zalogowa<e6> si<ea> do Protona.\n" 
```

So polish signs are specially converted.

**Comment by pbiecek** [comment]
I see, old version was working on R 3.2,
My today's fix was working on R 3.1
but is not on R 3.2
The problem is with default encoding of R, different in different versions.

Will fix in a second.

2015-11-23 23:33 GMT+01:00 Witold Chodor notifications@github.com:

> Reopened #10 https://github.com/BetaAndBit/PieczaraPietraszki/issues/10.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/10#event-472647601
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
Could you verify if current version is ok?

2015-11-23 23:44 GMT+01:00 Przemyslaw Biecek przemyslaw.biecek@gmail.com:

> I see, old version was working on R 3.2,
> My today's fix was working on R 3.1
> but is not on R 3.2
> The problem is with default encoding of R, different in different versions.
> 
> Will fix in a second.
> 
> 2015-11-23 23:33 GMT+01:00 Witold Chodor notifications@github.com:
> 
> > Reopened #10 https://github.com/BetaAndBit/PieczaraPietraszki/issues/10
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/BetaAndBit/PieczaraPietraszki/issues/10#event-472647601
> > .
> 
> ## 
> 
> pozdrawiam serdecznie,
> Przemysław Biecek

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
smart_icnonv:)
Works perfectly!
Thanks for you help!

**Comment by pbiecek** [comment]
Thanks for noticing this error

2015-11-23 23:55 GMT+01:00 Witold Chodor notifications@github.com:

> smart_icnonv:)
> Works perfectly!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/10#issuecomment-159093834
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek
