### ISSUE TITLE
logs instead of loggings?

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/PieczaraPietraszki#2]
What do you think about using 'logs' instead of 'loggings' as a name for data frame with logging information?
It's shorter and refers to analysis of logs.

**Comment by wchodor** [comment]
I found here:
http://dictionary.reference.com/browse/logging?s=t
that log may be: a register of the operation of a machine.  When it comes to logging there was no such definition.
I guess that I will hava to change loggings into logs not only in the name of data frame but also in the text.
