### ISSUE TITLE
Different versions of `roxygen2`

### ISSUE THREAD

**Issue by wchodor** [BetaAndBit/PieczaraPietraszki#3]
I don't think that it's a problem but have you noticed that we are using different versions of `roxygen2`?

**Comment by pbiecek** [comment]
It affects only Rd files, so I would not bother.

2015-11-19 12:49 GMT+01:00 Witold Chodor notifications@github.com:

> I don't think that it's a problem but have you noticed that we are using
> different versions of roxygen2?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/3.

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
OK
