### ISSUE TITLE
Name of the game

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/PieczaraPietraszki#4]
In the package description we have
Infiltration of the proton server.

In the proton() function there is 
Hack into Proton

What name should we use?

Other options:
Hacking into Proton
The Proton challenge

**Comment by wchodor** [comment]
My translation "Hack into Proton" means "Włam się do Protona". "Hacking into Proton" is more like "Włamanie do Protona". To be honest, I am not a fan of changing the meaning of a title while translating so: "Infiltration of the proton server" and "the Proton challenge" are not my favourite ones.
But you are the author and the final decision is up to you.

**Comment by pbiecek** [comment]
Yes, I have just doubts related to the way how 'hack into proton' sounds. 
Maybe 'Hack the Proton' or just 'The Proton Game'. 
Also I am a bit afraid of negative connotations that some people have when talking about 'hacking'. 
Maybe I  will run a short survey related to the title?

**Comment by wchodor** [comment]
It's a good idea.

**Comment by pbiecek** [comment]
The Proton Game and Hack the Proton got 10 votes each,
Infiltration of the proton server and The Proton challenge 3
Into the Proton and Hack into Proton 1
A tie again, 
I will use 'The Proton Game' in the game itself and 'Hack the Proton' in the blog post and in ads

**Comment by wchodor** [comment]
Won't it be confusing? If I were you, I would keep with one name.

**Comment by pbiecek** [comment]
Right,
so let's keep the 'The Proton Game'
If the package is to be used by teachers, they may be more reluctant withe
the 'Hack The Proton'.

2015-11-23 21:38 GMT+01:00 Witold Chodor notifications@github.com:

> Won't it be confusing? If I were you, I would keep with one name.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/PieczaraPietraszki/issues/4#issuecomment-159057558
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek
