### ISSUE TITLE
Localisation of 'employees' data set

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/PieczaraPietraszki#5]
English names and surnames

**Comment by pbiecek** [comment]
Names: http://names.mongabay.com/male_names.htm
Surnames: http://surnames.behindthename.com/top/lists/united-states/1990

**Comment by wchodor** [comment]
I have just created `employees` database. Tell me what do you think about it?

**Comment by pbiecek** [comment]
Great, good job. 
In the last column there were some duplicates, I've removed them.

**Comment by wchodor** [comment]
I didn't expect that male and female names could be the same? But it occurs that they can :).
